sudo: required

services:
  - docker

before_install:
  - cp .env.test .env
  - docker-compose up -d
  - docker-compose exec web COMPOSER_MEMORY_LIMIT=-1 composer install --no-interaction
  - docker-compose exec web php bin/console doctrine:schema:update --force
  - docker-compose exec web php bin/console hautelook:fixtures:load -q --purge-with-truncate

script:
  - composer validate
  - docker-compose exec web php bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction
  - docker-compose exec web SYMFONY_DEPRECATIONS_HELPER=max[self]=0 php bin/phpunit
  - docker-compose exec web php bin/phpunit
