sudo: required

services:
  - docker

before_install:
  - openssl aes-256-cbc -K $encrypted_4f5ac0744858_key -iv $encrypted_4f5ac0744858_iv -in config/jwt/public.pem.enc -out config/jwt/public.pem -d
  - openssl aes-256-cbc -K $encrypted_c312156a8ea8_key -iv $encrypted_c312156a8ea8_iv -in config/jwt/private.pem.enc -out config/jwt/private.pem -d
  - openssl aes-256-cbc -K $encrypted_3c84dcdc6bbe_key -iv $encrypted_3c84dcdc6bbe_iv -in .env.enc -out .env -d
  - docker-compose up -d
  - docker exec web bash -c "COMPOSER_MEMORY_LIMIT=-1 composer install --no-interaction"
  - mkdir config/jwt

script:
  - composer validate
  - docker-compose exec web php bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction
  - docker-compose exec web php bin/console doctrine:schema:update --force
  - docker-compose exec web php bin/console hautelook:fixtures:load -q --purge-with-truncate
  - docker exec web bash -c "SYMFONY_DEPRECATIONS_HELPER=max[self]=0 php bin/phpunit"
  - docker-compose down
