sudo: required

services:
  - docker

before_install:
  - cp .env.dist .env
  - docker-compose up -d
  - docker exec web bash -c "COMPOSER_MEMORY_LIMIT=-1 composer install --no-interaction"
  - mkdir config/jwt
  - openssl genrsa -out config/jwt/private2.pem -aes256 -passout pass:foobar 4096
  - openssl rsa -pubout -in config/jwt/private2.pem  -passin pass:foobar -out config/jwt/public2.pem

script:
  - composer validate
  - docker-compose exec web php bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction
  - docker-compose exec web php bin/console doctrine:schema:update --force
  - docker-compose exec web php bin/console hautelook:fixtures:load -q --purge-with-truncate
  - docker exec web bash -c "SYMFONY_DEPRECATIONS_HELPER=max[self]=0 php bin/phpunit"
  - docker-compose down
