jms_serializer:
    visitors:
        xml_serialization:
            format_output: '%kernel.debug%'
            encoding: 'UTF-8'
        json_serialization:
            options: ['JSON_PRETTY_PRINT', 'JSON_UNESCAPED_SLASHES']